---
- name: Pre-installation tasks
  hosts: all
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Set hostname on server1
      hostname:
        name: "{{ hostname_server1 }}"
      when: inventory_hostname == 'server1'

    - name: Set hostname on server2
      hostname:
        name: "{{ hostname_server2 }}"
      when: inventory_hostname == 'server2'

    - name: Update /etc/hosts with server1
      lineinfile:
        path: /etc/hosts
        line: "{{ ip_server1 }} {{ hostname_server1 }}"
        create: yes
      when: inventory_hostname == 'server1' or inventory_hostname == 'server2'

    - name: Update /etc/hosts with server2
      lineinfile:
        path: /etc/hosts
        line: "{{ ip_server2 }} {{ hostname_server2 }}"
        create: yes
      when: inventory_hostname == 'server1' or inventory_hostname == 'server2'

    - name: Reboot the server
      reboot:
        reboot_timeout: 300  # Timeout in seconds to wait for reboot to complete
        test_command: uptime
      async: 1
      poll: 0

